# Generated by Django 5.0.1 on 2024-09-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_wing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="wing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ARMY", "ARMY"),
                    ("NAVY", "NAVY"),
                    ("AIR FORCE", "AIR FORCE"),
                    ("TECHNOLOGY", "TECHNOLOGY"),
                    ("ANONYMOUS Media", "ANONYMOUS Media"),
                    ("DIGITAL ART", "DIGITAL ART"),
                    ("CONTENT CREATION", "CONTENT CREATION"),
                    ("SOCIAL ACTIVISM", "SOCIAL ACTIVISM"),
                    ("MENTAL WELLNESS", "MENTAL WELLNESS"),
                    ("HOBBIES & INTERESTS", "HOBBIES & INTERESTS"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userreport",
            name="reason",
            field=models.CharField(
                choices=[
                    ("SPAM", "SPAM"),
                    ("INAPPROPRIATE", "INAPPROPRIATE"),
                    ("HARASSMENT", "HARASSMENT"),
                    ("HATE SPEECH", "HATE SPEECH"),
                    ("FAKE NEWS", "FAKE NEWS"),
                    ("IMPERSONATION", "IMPERSONATION"),
                    ("OBSCENE CONTENT", "OBSCENE CONTENT"),
                    ("SEXUAL CONTENT", "SEXUAL CONTENT"),
                    ("VIOLENCE", "VIOLENCE"),
                    ("PLAGIARISM", "PLAGIARISM"),
                    ("SCAM", "SCAM"),
                    ("UNSAFE LINKS", "UNSAFE LINKS"),
                    ("MALICIOUS CONTENT", "MALICIOUS CONTENT"),
                    ("THREATENING BEHAVIOR", "THREATENING BEHAVIOR"),
                    ("MATURE CONTENT", "MATURE CONTENT"),
                    ("SELF-HARM", "SELF-HARM"),
                ],
                max_length=50,
            ),
        ),
    ]
