# Generated by Django 5.0.1 on 2024-09-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_twit_tagged_users_twitcomment_twitreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="post_videos"),
        ),
        migrations.AlterField(
            model_name="postreport",
            name="reason",
            field=models.CharField(
                choices=[
                    ("SPAM", "SPAM"),
                    ("INAPPROPRIATE", "INAPPROPRIATE"),
                    ("HARASSMENT", "HARASSMENT"),
                    ("HATE SPEECH", "HATE SPEECH"),
                    ("FAKE NEWS", "FAKE NEWS"),
                    ("IMPERSONATION", "IMPERSONATION"),
                    ("OBSCENE CONTENT", "OBSCENE CONTENT"),
                    ("SEXUAL CONTENT", "SEXUAL CONTENT"),
                    ("VIOLENCE", "VIOLENCE"),
                    ("PLAGIARISM", "PLAGIARISM"),
                    ("SCAM", "SCAM"),
                    ("UNSAFE LINKS", "UNSAFE LINKS"),
                    ("MALICIOUS CONTENT", "MALICIOUS CONTENT"),
                    ("THREATENING BEHAVIOR", "THREATENING BEHAVIOR"),
                    ("MATURE CONTENT", "MATURE CONTENT"),
                    ("SELF-HARM", "SELF-HARM"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="twitreport",
            name="reason",
            field=models.CharField(
                choices=[
                    ("SPAM", "SPAM"),
                    ("INAPPROPRIATE", "INAPPROPRIATE"),
                    ("HARASSMENT", "HARASSMENT"),
                    ("HATE SPEECH", "HATE SPEECH"),
                    ("FAKE NEWS", "FAKE NEWS"),
                    ("IMPERSONATION", "IMPERSONATION"),
                    ("OBSCENE CONTENT", "OBSCENE CONTENT"),
                    ("SEXUAL CONTENT", "SEXUAL CONTENT"),
                    ("VIOLENCE", "VIOLENCE"),
                    ("PLAGIARISM", "PLAGIARISM"),
                    ("SCAM", "SCAM"),
                    ("UNSAFE LINKS", "UNSAFE LINKS"),
                    ("MALICIOUS CONTENT", "MALICIOUS CONTENT"),
                    ("THREATENING BEHAVIOR", "THREATENING BEHAVIOR"),
                    ("MATURE CONTENT", "MATURE CONTENT"),
                    ("SELF-HARM", "SELF-HARM"),
                ],
                max_length=50,
            ),
        ),
    ]
