# Generated by Django 5.0.1 on 2024-03-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footer", "0002_alter_contact_id_alter_facts_id_alter_quote_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="link",
            field=models.TextField(default="#"),
        ),
    ]
