# Generated by Django 5.0.1 on 2024-03-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footer", "0003_quote_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="heading",
            field=models.TextField(default="Quotes"),
        ),
    ]
